/* Generated By:JavaCC: Do not edit this line. MeuParser.java */
package parser;

import java.io.*;

public class MeuParser implements MeuParserConstants {

/* 6. REGRA SINTÁTICA: O TESTADOR DO LÉXICO */
  final public void principal() throws ParseException {
  Token t;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PREPROCESSOR:
      case HEADER_LIB:
      case INT:
      case VOID:
      case UNSIGNED:
      case LONG:
      case RETURN:
      case IF:
      case ELSE:
      case WHILE:
      case FOR:
      case INCREMENT:
      case DECREMENT:
      case MULTIPLY_ASSIGN:
      case EQ:
      case NEQ:
      case LTE:
      case GTE:
      case PLUS:
      case MINUS:
      case MULTIPLY:
      case DIVIDE:
      case ASSIGN:
      case LT:
      case GT:
      case BITWISE_AND:
      case SEMICOLON:
      case COMMA:
      case LPAREN:
      case RPAREN:
      case LBRACE:
      case RBRACE:
      case INTEGER_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PREPROCESSOR:
        t = jj_consume_token(PREPROCESSOR);
                         System.out.println("Preprocessor: " + t.image);
        break;
      case HEADER_LIB:
        t = jj_consume_token(HEADER_LIB);
                       System.out.println("Header: " + t.image);
        break;
      case INT:
        t = jj_consume_token(INT);
                System.out.println("Keyword: " + t.image);
        break;
      case UNSIGNED:
        t = jj_consume_token(UNSIGNED);
                     System.out.println("Keyword: " + t.image);
        break;
      case LONG:
        t = jj_consume_token(LONG);
                 System.out.println("Keyword: " + t.image);
        break;
      case VOID:
        t = jj_consume_token(VOID);
                 System.out.println("Keyword: " + t.image);
        break;
      case RETURN:
        t = jj_consume_token(RETURN);
                   System.out.println("Keyword: " + t.image);
        break;
      case IF:
        t = jj_consume_token(IF);
               System.out.println("Keyword: " + t.image);
        break;
      case ELSE:
        t = jj_consume_token(ELSE);
                 System.out.println("Keyword: " + t.image);
        break;
      case FOR:
        t = jj_consume_token(FOR);
                System.out.println("Keyword: " + t.image);
        break;
      case WHILE:
        t = jj_consume_token(WHILE);
                  System.out.println("Keyword: " + t.image);
        break;
      case INCREMENT:
        t = jj_consume_token(INCREMENT);
                      System.out.println("Operator: " + t.image);
        break;
      case DECREMENT:
        t = jj_consume_token(DECREMENT);
                      System.out.println("Operator: " + t.image);
        break;
      case MULTIPLY_ASSIGN:
        t = jj_consume_token(MULTIPLY_ASSIGN);
                            System.out.println("Operator: " + t.image);
        break;
      case PLUS:
        t = jj_consume_token(PLUS);
                 System.out.println("Operator: " + t.image);
        break;
      case MINUS:
        t = jj_consume_token(MINUS);
                  System.out.println("Operator: " + t.image);
        break;
      case MULTIPLY:
        t = jj_consume_token(MULTIPLY);
                     System.out.println("Operator/Pointer: " + t.image);
        break;
      case DIVIDE:
        t = jj_consume_token(DIVIDE);
                   System.out.println("Operator: " + t.image);
        break;
      case ASSIGN:
        t = jj_consume_token(ASSIGN);
                   System.out.println("Operator: " + t.image);
        break;
      case EQ:
        t = jj_consume_token(EQ);
               System.out.println("Operator: " + t.image);
        break;
      case NEQ:
        t = jj_consume_token(NEQ);
                System.out.println("Operator: " + t.image);
        break;
      case LT:
        t = jj_consume_token(LT);
               System.out.println("Operator: " + t.image);
        break;
      case LTE:
        t = jj_consume_token(LTE);
                System.out.println("Operator: " + t.image);
        break;
      case GT:
        t = jj_consume_token(GT);
               System.out.println("Operator: " + t.image);
        break;
      case GTE:
        t = jj_consume_token(GTE);
                System.out.println("Operator: " + t.image);
        break;
      case BITWISE_AND:
        t = jj_consume_token(BITWISE_AND);
                        System.out.println("Pointer/Address: " + t.image);
        break;
      case SEMICOLON:
        t = jj_consume_token(SEMICOLON);
                      System.out.println("Delimiter: " + t.image);
        break;
      case COMMA:
        t = jj_consume_token(COMMA);
                  System.out.println("Delimiter: " + t.image);
        break;
      case LPAREN:
        t = jj_consume_token(LPAREN);
                   System.out.println("Delimiter: " + t.image);
        break;
      case RPAREN:
        t = jj_consume_token(RPAREN);
                   System.out.println("Delimiter: " + t.image);
        break;
      case LBRACE:
        t = jj_consume_token(LBRACE);
                   System.out.println("Delimiter: " + t.image);
        break;
      case RBRACE:
        t = jj_consume_token(RBRACE);
                   System.out.println("Delimiter: " + t.image);
        break;
      case INTEGER_LITERAL:
        t = jj_consume_token(INTEGER_LITERAL);
                            System.out.println("Integer: " + t.image);
        break;
      case STRING_LITERAL:
        t = jj_consume_token(STRING_LITERAL);
                           System.out.println("String: " + t.image);
        break;
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
                       System.out.println("Identifier: " + t.image);
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(0);
  }

  /** Generated Token Manager. */
  public MeuParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[2];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x898fe780,0x898fe780,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xe7e7ff,0xe7e7ff,};
   }

  /** Constructor with InputStream. */
  public MeuParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MeuParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MeuParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public MeuParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MeuParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public MeuParser(MeuParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(MeuParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[56];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 2; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 56; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
