/* Generated By:JavaCC: Do not edit this line. MeuParserConstants.java */
package parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MeuParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRE_PROCESSADOR = 7;
  /** RegularExpression Id. */
  int BIBLIOTECA_CABECALHO = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int VOID = 10;
  /** RegularExpression Id. */
  int CARACTERE = 11;
  /** RegularExpression Id. */
  int FLOAT = 12;
  /** RegularExpression Id. */
  int SEM_SINAL = 13;
  /** RegularExpression Id. */
  int LONGO = 14;
  /** RegularExpression Id. */
  int RETORNO = 15;
  /** RegularExpression Id. */
  int SE = 16;
  /** RegularExpression Id. */
  int SENAO = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int PARE = 21;
  /** RegularExpression Id. */
  int CONTINUAR = 22;
  /** RegularExpression Id. */
  int INCREMENTO = 23;
  /** RegularExpression Id. */
  int DECREMENTO = 24;
  /** RegularExpression Id. */
  int ATRIBUICAO_SOMA = 25;
  /** RegularExpression Id. */
  int ATRIBUICAO_SUBTRACAO = 26;
  /** RegularExpression Id. */
  int ATRIBUICAO_MULTIPLICACAO = 27;
  /** RegularExpression Id. */
  int ATRIBUICAO_DIVISAO = 28;
  /** RegularExpression Id. */
  int E_LOGICO = 29;
  /** RegularExpression Id. */
  int OU_LOGICO = 30;
  /** RegularExpression Id. */
  int IGUAL = 31;
  /** RegularExpression Id. */
  int DIFERENTE = 32;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 33;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 34;
  /** RegularExpression Id. */
  int MAIS = 35;
  /** RegularExpression Id. */
  int MENOS = 36;
  /** RegularExpression Id. */
  int ASTERISCO = 37;
  /** RegularExpression Id. */
  int DIVISAO = 38;
  /** RegularExpression Id. */
  int ATRIBUICAO = 39;
  /** RegularExpression Id. */
  int MENOR = 40;
  /** RegularExpression Id. */
  int MAIOR = 41;
  /** RegularExpression Id. */
  int E_COMERCIAL = 42;
  /** RegularExpression Id. */
  int OU_BIT_A_BIT = 43;
  /** RegularExpression Id. */
  int NEGACAO = 44;
  /** RegularExpression Id. */
  int PONTO_E_VIRGULA = 45;
  /** RegularExpression Id. */
  int VIRGULA = 46;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 47;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 48;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 49;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 50;
  /** RegularExpression Id. */
  int ABRE_COLCHETES = 51;
  /** RegularExpression Id. */
  int FECHA_COLCHETES = 52;
  /** RegularExpression Id. */
  int LITERAL_INTEIRO = 53;
  /** RegularExpression Id. */
  int LITERAL_FLUTUANTE = 54;
  /** RegularExpression Id. */
  int EXPONENCIAL = 55;
  /** RegularExpression Id. */
  int LITERAL_TEXTO = 56;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<PRE_PROCESSADOR>",
    "<BIBLIOTECA_CABECALHO>",
    "\"int\"",
    "\"void\"",
    "\"char\"",
    "\"float\"",
    "\"unsigned\"",
    "\"long\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"do\"",
    "\"break\"",
    "\"continue\"",
    "\"++\"",
    "\"--\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<LITERAL_INTEIRO>",
    "<LITERAL_FLUTUANTE>",
    "<EXPONENCIAL>",
    "<LITERAL_TEXTO>",
    "<IDENTIFICADOR>",
  };

}
