/* Generated By:JavaCC: Do not edit this line. MeuParserConstants.java */
package parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MeuParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PREPROCESSOR = 7;
  /** RegularExpression Id. */
  int HEADER_LIB = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int VOID = 10;
  /** RegularExpression Id. */
  int CHAR = 11;
  /** RegularExpression Id. */
  int FLOAT = 12;
  /** RegularExpression Id. */
  int UNSIGNED = 13;
  /** RegularExpression Id. */
  int LONG = 14;
  /** RegularExpression Id. */
  int RETURN = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int BREAK = 21;
  /** RegularExpression Id. */
  int CONTINUE = 22;
  /** RegularExpression Id. */
  int INCREMENT = 23;
  /** RegularExpression Id. */
  int DECREMENT = 24;
  /** RegularExpression Id. */
  int PLUS_ASSIGN = 25;
  /** RegularExpression Id. */
  int MINUS_ASSIGN = 26;
  /** RegularExpression Id. */
  int MULTIPLY_ASSIGN = 27;
  /** RegularExpression Id. */
  int DIVIDE_ASSIGN = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int EQ = 31;
  /** RegularExpression Id. */
  int NEQ = 32;
  /** RegularExpression Id. */
  int LTE = 33;
  /** RegularExpression Id. */
  int GTE = 34;
  /** RegularExpression Id. */
  int PLUS = 35;
  /** RegularExpression Id. */
  int MINUS = 36;
  /** RegularExpression Id. */
  int MULTIPLY = 37;
  /** RegularExpression Id. */
  int DIVIDE = 38;
  /** RegularExpression Id. */
  int ASSIGN = 39;
  /** RegularExpression Id. */
  int LT = 40;
  /** RegularExpression Id. */
  int GT = 41;
  /** RegularExpression Id. */
  int BITWISE_AND = 42;
  /** RegularExpression Id. */
  int BITWISE_OR = 43;
  /** RegularExpression Id. */
  int NOT = 44;
  /** RegularExpression Id. */
  int SEMICOLON = 45;
  /** RegularExpression Id. */
  int COMMA = 46;
  /** RegularExpression Id. */
  int LPAREN = 47;
  /** RegularExpression Id. */
  int RPAREN = 48;
  /** RegularExpression Id. */
  int LBRACE = 49;
  /** RegularExpression Id. */
  int RBRACE = 50;
  /** RegularExpression Id. */
  int LBRACKET = 51;
  /** RegularExpression Id. */
  int RBRACKET = 52;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 53;
  /** RegularExpression Id. */
  int STRING_LITERAL = 54;
  /** RegularExpression Id. */
  int IDENTIFIER = 55;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<PREPROCESSOR>",
    "<HEADER_LIB>",
    "\"int\"",
    "\"void\"",
    "\"char\"",
    "\"float\"",
    "\"unsigned\"",
    "\"long\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"do\"",
    "\"break\"",
    "\"continue\"",
    "\"++\"",
    "\"--\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
  };

}
